### ISSUE TITLE
Typo in [content/blog/caching-everything-for-totally-offline-pwa-vite-react/index.md] Line 62

### ISSUE THREAD

**Issue by mosespace** [adueck/blog#1]
Title: Typo in `content/blog/caching-everything-for-totally-offline-pwa-vite-react/index.md`

Description:
Hello, @adueck . Hope your doing good. In the above mention location, there is a spelling mistake in the first paragraph. The word `"folter"`[^1] is spelled incorrectly and should be corrected to `"folder"`. This mistake may affect the professionalism of the website, so it should be fixed as soon as possible. I can resolve the above problem! if given chance!

Steps to reproduce:

Navigate to the `content/blog/caching-everything-for-totally-offline-pwa-vite-react/index.md` page of the blog.
Head over to line 62.
Observe the spelling mistake in the word "folter".
Proposed fix:
Change the spelling of the word "folter" to `"folder"` at line 62 of the above given address.

Screenshot:
[^1]: ![image](https://user-images.githubusercontent.com/111237257/228361596-8efb2790-1cfa-4531-ae2c-e29a5d920fd1.png)

Let me know if you have any further suggestions!

**Comment by adueck** [comment]
Thanks @mosespace for catching this. I just fixed it!
